// GENERATED by tools/gen_lsp_builtins.py — do not edit by hand.
// Re-run the script after adding methods to evaluator namespaces.

/// Native namespaces and their methods, extracted from the evaluator.
pub static NAMESPACES: &[(&str, &[&str])] = &[
    ("Autodiff", &["adamStep", "adamwStep", "backward", "batchNorm", "bceLoss", "clear", "clipGrad", "clipGradNorm", "crossEntropyLoss", "detach", "dropout", "embedding", "gradient", "heNormal", "heUniform", "isRecording", "loadWeights", "maeLoss", "mseLoss", "rmspropStep", "saveWeights", "sgdStep", "stopGrad", "tape", "xavierNormal", "xavierUniform"]),
    ("Binary", &["concat", "fromHex", "fromUtf8", "packInt32Be", "packInt32Le", "packInt64Le", "toHex", "toUtf8", "unpackInt32Be", "unpackInt32Le", "unpackInt64Le"]),
    ("Crypto", &["base64decode", "base64encode", "ed25519Keypair", "ed25519Sign", "ed25519Verify", "hexDecode", "hexEncode", "hmacSha256", "md5", "randomBytes", "sha1", "sha1base64", "sha256"]),
    ("DateTime", &["from", "fromEpoch", "fromTimestamp", "now", "utcNow"]),
    ("Dec", &["MAX", "MAX_SCALE", "MIN", "fromInt", "parse"]),
    ("Env", &["args", "get", "set"]),
    ("File", &["create", "delete", "exists", "listDir", "mkdir", "read", "read_asBinary", "rename", "stat", "write", "write_asBinary"]),
    ("GPU", &["axpy", "createBuffer", "createBufferFromArray", "dot", "fill", "freeBuffer", "map", "matmul", "readBuffer", "reduce", "size"]),
    ("Gui", &["blur", "charsTyped", "clear", "clipboardGet", "clipboardGetImage", "clipboardSet", "clipboardSetImage", "close", "closeWindow", "currentWindow", "dragWindow", "drawCircle", "drawImage", "drawLine", "drawLineThick", "drawPolyline", "drawRect", "drawText", "droppedFiles", "fillCircle", "fillGradient", "fillPolygon", "fillRect", "fillRectAlpha", "fillRoundRect", "focused", "font", "hoveredFiles", "idleWait", "imageSize", "imePreedit", "isOpen", "keyDown", "keysPressed", "keysReleased", "keysRepeated", "loadFont", "loadImage", "loadImageBytes", "measureText", "monitors", "mouse", "mouseBackDown", "mouseDown", "mouseForwardDown", "mouseInWindow", "mouseMiddleDown", "mousePressed", "mouseRightDown", "nodeCircle", "nodeClipPop", "nodeClipPush", "nodeCount", "nodeDelete", "nodeImage", "nodeLine", "nodePolygon", "nodePolyline", "nodeRect", "nodeRectAlpha", "nodeRectOutline", "nodeRoundRect", "nodeSet", "nodeText", "open", "openFileDialog", "openWindow", "pinchDelta", "popClip", "present", "pushClip", "renderScene", "saveFileDialog", "scaleFactor", "sceneClear", "scroll", "selectWindow", "setCursor", "setCursorImage", "setFont", "setImePosition", "setPixel", "setTitle", "setWindowIcon", "size", "textAdvances", "time", "touches", "windowPosition"]),
    ("JSON", &["parse", "pretty", "stringify"]),
    ("Math", &["E", "PI", "atan2", "clamp", "max", "min", "pow", "random", "sign"]),
    ("Media", &["isPlaying", "pause", "playSound", "playingCount", "resume", "setVolume", "stop", "stopAll"]),
    ("Memory", &["alloc", "copy", "fill", "free", "offsetOf", "read", "size", "sizeof", "write"]),
    ("OS", &["exec", "kill", "pid", "platform", "spawn", "tick"]),
    ("Random", &["bernoulli", "choice", "decimal", "int", "normal", "normalTensor", "seed", "shuffle", "uniform", "uniformTensor"]),
    ("Regex", &["findAll", "match", "replace", "split", "test"]),
    ("Socket", &["accept", "close", "connect", "listen", "recv", "recvWsFrame", "send", "sendWsFrame"]),
    ("System", &["cpuCount", "freeMemory", "hostname", "totalMemory", "uptime"]),
    ("Task", &["isDone", "message", "poll", "reply", "run"]),
    ("Tensor", &["eye", "from", "ones", "zeros"]),
    ("Terminal", &["clear", "enableMouse", "getSize", "readByte", "readEvent", "setCursor", "setRawMode", "writeByte"]),
    ("Time", &["now", "sleep"]),
];

/// Methods available on values (arrays, strings, sets, dec, tensors).
pub static VALUE_METHODS: &[(&str, &[&str])] = &[
    ("array", &["contains", "every", "filter", "find", "findIndex", "flat", "includes", "indexOf", "join", "length", "map", "pop", "push", "reduce", "remove", "reverse", "shift", "slice", "some", "sort", "toString", "unshift"]),
    ("dec", &["MAX", "MAX_SCALE", "MIN", "abs", "ceil", "floor", "fromInt", "isZero", "max", "min", "parse", "round", "scale", "setScale", "sign", "toDecimal", "toInt", "toString", "truncate"]),
    ("set", &["add", "clear", "contains", "delete", "has", "intersection", "remove", "size", "toArray", "toString", "union"]),
    ("string", &["charAt", "contains", "endsWith", "includes", "indexOf", "length", "lower", "padEnd", "padStart", "replace", "replaceAll", "slice", "split", "startsWith", "substring", "toLowerCase", "toString", "toUpperCase", "trim", "trimEnd", "trimLeft", "trimRight", "trimStart", "upper"]),
    ("tensor", &["abs", "add", "argmax", "argmin", "avg_pool2d", "bmm", "broadcastAdd", "broadcastAddNd", "broadcastDiv", "broadcastMul", "broadcastMulNd", "broadcastSub", "broadcastTo", "ceil", "clamp", "concat", "conv2d", "cos", "cumsum", "detach", "div", "dot", "elu", "exp", "eye", "fill", "flatten", "floor", "from", "gelu", "get", "gru", "hardsigmoid", "hardswish", "layer_norm", "leaky_relu", "leaky_relu_tracked", "log", "lstm", "matmul", "max", "max_pool2d", "maximum", "mean", "meanAxis", "mha", "min", "minimum", "mish", "mul", "ndim", "neg", "norm", "one_hot", "ones", "outer", "permute", "pow", "reciprocal", "reduceMax", "reduceMean", "reduceSum", "relu", "reshape", "round", "scale", "set", "shape", "sigmoid", "sign", "silu", "sin", "size", "slice", "softmax", "softplus", "sqrt", "squeeze", "std", "stopGrad", "sub", "sum", "sumAxis", "swish", "tanh", "toArray", "toString", "transpose", "unsqueeze", "variance", "zeros"]),
];
